<a href="https://colab.research.google.com/github/satyamsingh1004/ML/blob/master/RNNs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

import numpy as np

In [0]:
n_inputs = 3
n_neurons = 5

In [0]:
X0 = tf.placeholder(tf.float32,[None,n_inputs])
X1 = tf.placeholder(tf.float32,[None,n_inputs])

In [0]:
Wx= tf.Variable(tf.random_normal(shape=[n_inputs,n_neurons],dtype=tf.float32))
Wy= tf.Variable(tf.random_normal(shape=[n_neurons,n_neurons],dtype=tf.float32))

b = tf.Variable(tf.zeros([1,n_neurons],dtype=tf.float32))

In [0]:
Y0 = tf.tanh(tf.matmul(X0,Wx) + b)
Y1 = tf.tanh(tf.matmul(Y0,Wy) + tf.matmul(X1,Wx) + b)

init = tf.global_variables_initializer()

In [0]:
X0_batch = np.array([[0,1,2],[3,4,5],[6,7,8],[9,0,1]])
X1_batch = np.array([[9, 8, 7], [0, 0, 0], [6, 5, 4], [3, 2, 1]])

In [0]:
with tf.Session() as sess:
  init.run()
  Y0_val, Y1_val  = sess.run([Y0,Y1],feed_dict={X0: X0_batch, X1: X1_batch})

In [19]:
print(Y0_val)
print(Y1_val)

[[ 0.9159313   0.6829919   0.9926684  -0.6563761   0.06895255]
 [ 0.9056463   0.96579367  0.9982176  -0.9999987   0.94138986]
 [ 0.8941725   0.99679023  0.9995676  -1.          0.99790925]
 [-0.99999833 -0.71363574 -1.         -1.          0.9593621 ]]
[[-0.9227866   0.99958146 -0.69239944 -1.          0.98398536]
 [-0.3025733   0.94310373 -0.9764612   0.71895814 -0.99651575]
 [-0.96539366  0.997232   -0.99888736 -1.          0.09422377]
 [-0.9888231   0.8041291  -0.99982464 -0.99999994  0.9978334 ]]


Dynamic Rnns

In [21]:
X = tf.placeholder(tf.float32,[None,n_steps,n_inputs])
basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
outputs, states = tf.nn.dynamic_rnn(basic_cell,X,dtype=tf.float32)

W0629 05:19:50.364288 140358404659072 deprecation.py:323] From <ipython-input-21-ac7265594ec4>:3: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API


ValueError: ignored